#!/usr/bin/env sh

set -xeo pipefail

DOCKER_IMAGE_NAME="snapkitchen/concourse-terraform-resource"

# main

terraform_versions=($(cat tf-versions))

for terraform_version in "${terraform_versions[@]}"
do
  test_image="${DOCKER_IMAGE_NAME}-tests:${terraform_version}"
  docker \
    run \
      -i \
      --rm \
      "${test_image}" python -m unittest discover
done
