#!/usr/bin/env bash

set -xeo pipefail

DOCKER_IMAGE_NAME="snapkitchen/concourse-terraform-resource"

# main

if [[ -n "${1:-}" ]]
then
  # run specific version
  test_image="${DOCKER_IMAGE_NAME}-tests:${1}"
  explicit_test_command_args=("${@:2}")
  test_command_args=('python' '-m' 'unittest')
  if [[ "${#explicit_test_command_args[@]}" -gt 0 ]]
  then
    test_command_args+=("${explicit_test_command_args[@]}")
  else
    test_command_args+=('discover')
  fi
  docker \
    run \
      -i \
      --rm \
      "${test_image}" ${test_command_args[@]+"${test_command_args[@]}"}
else
  # run all supported versions
  terraform_versions=($(cat tf-versions))

  for terraform_version in "${terraform_versions[@]}"
  do
    test_image="${DOCKER_IMAGE_NAME}-tests:${terraform_version}"
    docker \
      run \
        -i \
        --rm \
        "${test_image}" python -m unittest discover
  done
fi
