#!/usr/bin/env sh

set -xeo pipefail

DOCKER_IMAGE_NAME="snapkitchen/concourse-terraform-resource"
DOCKER_IMAGE_TAG="latest"

terraform_version="${1}"

if [ -n "${terraform_version}" ]
then
  DOCKER_IMAGE_TAG="${terraform_version}"
fi

test_image="${DOCKER_IMAGE_NAME}-tests:${DOCKER_IMAGE_TAG}"

docker \
  run \
    -i \
    --rm \
    "${test_image}" python -m unittest discover
