resources:

# source code
# ===========
- name: concourse-terraform
  type: git
  source:
    uri: https://github.com/Snapkitchen/concourse-terraform.git

# docker image
# ============
- name: concourse-terraform-image
  type: docker-image
  source:
    repository: snapkitchen/concourse-terraform
    tag: 0.11.10

jobs:
- name: plan
  plan:
  - get: concourse-terraform
  - get: concourse-terraform-image
  - task: plan
    image: concourse-terraform-image
    file: concourse-terraform/tasks/plan.yaml
    input_mapping:
      terraform-source-dir: concourse-terraform
    params:
      TF_WORKING_DIR: terraform-source-dir/testdata/terraform
      DEBUG: true

- name: plan-destroy
  plan:
  - get: concourse-terraform
  - get: concourse-terraform-image
  - task: plan-destroy
    image: concourse-terraform-image
    file: concourse-terraform/tasks/plan.yaml
    input_mapping:
      terraform-source-dir: concourse-terraform
    params:
      TF_WORKING_DIR: terraform-source-dir/testdata/terraform
      ERROR_ON_NO_CHANGES: false
      DESTROY: true
      DEBUG: true

- name: plan-existing-state
  plan:
  - get: concourse-terraform
  - get: concourse-terraform-image
  - task: plan
    image: concourse-terraform-image
    file: concourse-terraform/tasks/plan.yaml
    input_mapping:
      terraform-source-dir: concourse-terraform
    params:
      TF_WORKING_DIR: terraform-source-dir/testdata/terraform
      INPUT_STATE_FILE_PATH: terraform-source-dir/testdata/terraform-state/with-key.tfstate
      DEBUG: true
