#!/usr/bin/env bash
set -ex

terraform_versions=($(cat tf-versions))

for terraform_version in "${terraform_versions[@]}"
do
  echo "building image for version ${terraform_version}"
    docker build \
        --build-arg TERRAFORM_VERSION="${terraform_version}" \
        --tag "${IMAGE_NAME}:${terraform_version}" \
        .
  echo "building test image for version ${terraform_version}"
    docker build \
        --build-arg TERRAFORM_VERSION="${terraform_version}" \
        --tag "${IMAGE_NAME}-tests:${terraform_version}" \
        .
done

for terraform_version in "${terraform_versions[@]}"
do
  echo "running test image for version ${terraform_version}"
  docker \
    run \
      --rm \
      "${IMAGE_NAME}-tests:${terraform_version}" python -m unittest discover
done
