#!/usr/bin/env bash
set -ex

terraform_versions=($(cat tf-versions))

for terraform_version in "${terraform_versions[@]}"
do
  echo "building ${terraform_version}"
    docker build \
        --build-arg TERRAFORM_VERSION="${terraform_version}" \
        --tag "${DOCKER_REPO}:${terraform_version}" \
        .
done

# force failure
exit 1
