#!/usr/bin/env bash
set -ex

terraform_versions=($(cat tf-versions))

for terraform_version in "${terraform_versions[@]}"
do
  echo "pushing image for version ${terraform_version}"
  docker push "${IMAGE_NAME}:${terraform_version}"
done
