#!/usr/bin/env bash
set -ex

terraform_versions=($(cat tf-versions))

for terraform_version in "${terraform_versions[@]}"
do
  echo "pushing image for version ${terraform_version}"
  docker push "${DOCKER_REPO}:${terraform_version}"
  echo "pushing consul image for version ${terraform_version}"
  docker push "${DOCKER_REPO}:${terraform_version}-consul"
done
