#!/usr/bin/env bash

set -xeo pipefail

DOCKER_IMAGE_NAME="public.ecr.aws/g9q9d1i9/concourse-terraform"
DOCKER_REPO_URL="docker-registry.service.local.consul:5000"

push_app_image() {
  # req: app_image
  # req: terraform_version
  local local_app_image="${DOCKER_REPO_URL}/${app_image}"
  echo "pushing local app image ${local_app_image}"
  docker tag "${app_image}" "${local_app_image}"
  docker push "${local_app_image}"
}

push_consul_image() {
  # req: app_image
  # req: consul_image
  # req: consul_version
  # req: terraform_version
  local local_consul_image="${DOCKER_REPO_URL}/${consul_image}"
  echo "pushing local consul image ${local_consul_image}"
  docker tag "${consul_image}" "${local_consul_image}"
  docker push "${local_consul_image}"
}

push_test_image() {
  # req: consul_image
  # req: test_image
  local local_test_image="${DOCKER_REPO_URL}/${test_image}"
  echo "pushing local test image ${local_test_image}"
  docker tag "${test_image}" "${local_test_image}"
  docker push "${local_test_image}"
}

# main

if [[ -n "${1:-}" ]]
then
  # build specific version
  terraform_version="${1}"
  consul_version="$(cat consul-version)"
  app_image="${DOCKER_IMAGE_NAME}:${terraform_version}"
  consul_image="${DOCKER_IMAGE_NAME}:${terraform_version}-consul"
  test_image="${DOCKER_IMAGE_NAME}-tests:${terraform_version}"

  if push_app_image
  then
    push_consul_image
    push_test_image
  fi
else
  # build all supported versions
  terraform_versions=($(cat tf-versions))
  consul_version="$(cat consul-version)"

  for terraform_version in "${terraform_versions[@]}"
  do
    app_image="${DOCKER_IMAGE_NAME}:${terraform_version}"
    consul_image="${DOCKER_IMAGE_NAME}:${terraform_version}-consul"
    test_image="${DOCKER_IMAGE_NAME}-tests:${terraform_version}"

    if push_app_image
    then
      push_consul_image
      push_test_image
    fi
  done
fi
