#!/usr/bin/env bash

set -xeo pipefail

DOCKER_IMAGE_NAME="public.ecr.aws/g9q9d1i9/concourse-terraform"

# main

: "${1:?"image version"}"

# run specific version
test_image="${DOCKER_IMAGE_NAME}-tests:${1}"
run_command_args=("${@:2}")
docker \
  run \
    -it \
    --rm \
    "${test_image}" ${run_command_args[@]+"${run_command_args[@]}"}
